import YahooFinance from 'yahoo-finance2'
import type { AssetStats, Dividend, HistoricalPoint, MarketDataProvider, Period, Quote } from './types'

const yahoo = new YahooFinance({ suppressNotices: ['yahooSurvey'] })
const ranges: Record<Period, { period1: Date; interval: '1m' | '1h' | '1d' | '1wk' | '1mo' }> = {
  '1D': { period1: new Date(Date.now() - 86400000), interval: '1h' }, '1S': { period1: new Date(Date.now() - 7 * 86400000), interval: '1h' }, '1M': { period1: new Date(Date.now() - 30 * 86400000), interval: '1d' }, '3M': { period1: new Date(Date.now() - 90 * 86400000), interval: '1d' }, YTD: { period1: new Date(new Date().getFullYear(), 0, 1), interval: '1d' }, '1A': { period1: new Date(Date.now() - 365 * 86400000), interval: '1d' }, '5A': { period1: new Date(Date.now() - 5 * 365 * 86400000), interval: '1wk' }, 'Máx': { period1: new Date(Date.now() - 25 * 365 * 86400000), interval: '1mo' },
}
const safe = <T,>(value: T | undefined | null): T | null => value ?? null
const emptyQuote = (symbol: string): Quote => ({ symbol, price: null, previousClose: null, change: null, changePercent: null, currency: null, name: null })

export const provider: MarketDataProvider = {
  async getQuote(symbol) { try { const q = await yahoo.quote(symbol); const price = safe(q.regularMarketPrice); const previousClose = safe(q.regularMarketPreviousClose); return { symbol, price, previousClose, change: price !== null && previousClose !== null ? price - previousClose : null, changePercent: price !== null && previousClose ? ((price / previousClose) - 1) * 100 : null, currency: safe(q.currency), name: safe(q.longName || q.shortName) } } catch (error) { console.error(`[market-data] Error Yahoo Finance / ticker no encontrado: ${symbol}`, error); return emptyQuote(symbol) } },
  async getMultipleQuotes(symbols) { const entries = await Promise.all(symbols.map(async s => [s, await this.getQuote(s)] as const)); return Object.fromEntries(entries) },
  async getHistoricalPrices(symbol, period) { try { const result = await yahoo.chart(symbol, ranges[period]); return (result.quotes ?? []).filter(q => q.close != null).map(q => ({ date: new Date(q.date).toISOString(), close: q.close as number })) } catch (error) { console.error(`[market-data] Error histórico: ${symbol}`, error); return [] } },
  async getAssetStats(symbol) { try { const q = await yahoo.quoteSummary(symbol, { modules: ['price', 'summaryDetail', 'defaultKeyStatistics'] }); const p = q.price; const d = q.summaryDetail; const k = q.defaultKeyStatistics; return { dayHigh: safe(p?.regularMarketDayHigh), dayLow: safe(p?.regularMarketDayLow), fiftyTwoWeekHigh: safe<number>(p?.fiftyTwoWeekHigh as number | undefined), fiftyTwoWeekLow: safe<number>(p?.fiftyTwoWeekLow as number | undefined), volume: safe(p?.regularMarketVolume), averageVolume: safe(d?.averageVolume), marketCap: safe(p?.marketCap), pe: safe<number>((k?.forwardPE || k?.trailingPE) as number | undefined), dividendYield: safe(d?.dividendYield) } } catch (error) { console.error(`[market-data] Error estadísticas: ${symbol}`, error); return { dayHigh: null, dayLow: null, fiftyTwoWeekHigh: null, fiftyTwoWeekLow: null, volume: null, averageVolume: null, marketCap: null, pe: null, dividendYield: null } } },
  async getDividendHistory(symbol) { try { const result = await yahoo.chart(symbol, { period1: new Date(Date.now() - 5 * 365 * 86400000), interval: '1mo', events: 'dividends' }); return (result.events?.dividends ?? []).map((d: { date: Date; amount: number }) => ({ date: new Date(d.date).toISOString(), amount: d.amount })) } catch (error) { console.error(`[market-data] Error dividendos: ${symbol}`, error); return [] } },
  async getFxRate(from, to) { if (from === to) return 1; try { const q = await this.getQuote(`${from}${to}=X`); return q.price ?? 1 } catch (error) { console.error(`[market-data] FX no disponible: ${from}/${to}`, error); return 1 } },
}
