'use client'
import { useState } from 'react'
import { currencies, getPortfolioPosition, savePortfolioPosition, type CostCurrency } from '@/lib/positions'
export function PositionEditor({ symbol, onSaved }: { symbol: string; onSaved?: () => void }) {
  const existing = getPortfolioPosition(symbol)
  const [open, setOpen] = useState(false); const [quantity, setQuantity] = useState(String(existing?.quantity ?? '')); const [averageCost, setAverageCost] = useState(String(existing?.averageCost ?? '')); const [costCurrency, setCostCurrency] = useState<CostCurrency>(existing?.costCurrency ?? 'EUR')
  function save() { const q = Number(quantity), c = Number(averageCost); if (!Number.isFinite(q) || q <= 0 || !Number.isFinite(c) || c < 0) return; savePortfolioPosition(symbol, { quantity: q, averageCost: c, costCurrency }); setOpen(false); onSaved?.() }
  return <><button onClick={() => setOpen(true)} className="w-full rounded-full py-4 font-bold" style={{background:'var(--color-positive)',color:'#000'}}>{existing ? 'Editar portfolio' : 'Añadir al portfolio'}</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="edit-position-title"><div className="w-full max-w-md rounded-xl p-6" style={{background:'var(--color-panel)'}}><h2 id="edit-position-title" className="text-2xl font-bold mb-6">Editar {symbol}</h2><div className="flex flex-col gap-4"><label className="flex flex-col gap-2">Cantidad<input type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} className="rounded-lg p-3" style={{background:'var(--color-control)',color:'inherit'}} /></label><label className="flex flex-col gap-2">Coste promedio<input type="number" min="0" step="any" value={averageCost} onChange={e=>setAverageCost(e.target.value)} className="rounded-lg p-3" style={{background:'var(--color-control)',color:'inherit'}} /></label><label className="flex flex-col gap-2">Moneda<select value={costCurrency} onChange={e=>setCostCurrency(e.target.value as CostCurrency)} className="rounded-lg p-3" style={{background:'var(--color-control)',color:'inherit'}}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="flex justify-end gap-3 mt-8"><button onClick={()=>setOpen(false)} className="rounded-lg px-5 py-3">Cancelar</button><button onClick={save} className="rounded-lg px-5 py-3 font-bold" style={{background:'var(--color-positive)',color:'#000'}}>Guardar</button></div></div></div>}</>
}
